apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-api
  name: account-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: account-api
  replicas: 3
  template:
    metadata:
      labels:
        app: account-api
    spec:
      containers:
        - name: account-api
          image: crbm/account-api:latest
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: "/app/secret"
              name: secret
              readOnly: true
          ports:
            - containerPort: 3333
      volumes:
        - name: secret
          secret:
            secretName: account-api-secrets-278ckmmkdg
