name: Docker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node
        with:
          node-version: 13.x
      - name: Install dependencies
        working-directory: ./biosimulations
        run: npm ci && npm install -g @nrwl/cli
      - name: Build
        working-directory: ./biosimulations
        run: nx build --prod
      - name: Build front end Docker image
        run: docker build . --file Dockerfile.frontend --tag biosimulations_frontend:$(date +%s)
